Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Session;
using Customer.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Text.Json;

namespace Customer.Controllers
{
    public class CartController : Controller
    {
        WebsiteBanDoAnContext ctx = new WebsiteBanDoAnContext();
        public IActionResult ShoppingCart()
        {
            var sessionId = HttpContext.Session.Id;
            ViewBag.sessionId = sessionId;
            ViewBag.Title = "ShoppingCart";

            List<ItemCart> items = null;
            // doc session
            var yourcart = HttpContext.Session.GetString("yourcart");
            //chuyen string json --> object

            if (yourcart != null)
            {
                items = (List<ItemCart>)JsonSerializer.Deserialize(yourcart, typeof(List<ItemCart>));
            }
            else
            {
                items = new List<ItemCart>();
            }
            ViewBag.Cart = items;
            // total
            decimal total = 0;
            foreach (ItemCart item in items)
            {
                total += item.Price * item.Quantity;

            }
            ViewBag.Total = total;

            return View();
        }
        [HttpPost]
        public IActionResult AddToCart()
        {
            int id = int.Parse(Request.Form["MaSp"].ToString());
            int quantity = int.Parse(Request.Form["SoLuong"].ToString());

            List<ItemCart> items = null;

            var yourcart = HttpContext.Session.GetString("yourcart");


            if (yourcart != null)
            {
                items = (List<ItemCart>)JsonSerializer.Deserialize(yourcart, typeof(List<ItemCart>));
            }
            else
            {
                items = new List<ItemCart>();
            }

            MonAn prod = ctx.MonAns.Where(x => x.MaSp == id).SingleOrDefault();

            ItemCart item = new ItemCart()
            {
                Id = id,
                Quantity = quantity,
                Image = prod.HinhAnh,
                Price = (decimal)prod.GiaSp,
                Name = prod.TenSp,
            };

            items.Add(item);
            HttpContext.Session.SetString("yourcart", JsonSerializer.Serialize(items, typeof(List<ItemCart>)));

            return RedirectToAction("ShoppingCart");
        }
        public IActionResult Bill()
        {
            /*            var sessionId = HttpContext.Session.Id;
                        ViewBag.sessionId = sessionId;*/
            ViewBag.Title = "Hóa đơn";

            List<ItemCart> items = null;
            //doc session
            var yourcart = HttpContext.Session.GetString("yourcart");
            //chuyen string json --> object
            if (yourcart != null)
            {
                items = (List<ItemCart>)JsonSerializer.Deserialize(yourcart, typeof(List<ItemCart>));
            }
            else
            {
                items = new List<ItemCart>();
            }
            ViewBag.Cart = items;
            // total
            decimal total = 0;
            foreach (ItemCart item in items)
            {
                total += item.Price * item.Quantity;

            }
            ViewBag.Total = total;

            return View();
        }
        [HttpPost]
        public IActionResult Bill(HoaDon bill)
        {
            List<ItemCart> items = null;
            //doc session
            var yourcart = HttpContext.Session.GetString("yourcart");
            //chuyen string json --> object
            if (yourcart != null)
            {
                items = (List<ItemCart>)JsonSerializer.Deserialize(yourcart, typeof(List<ItemCart>));
            }
            else
            {
                items = new List<ItemCart>();
            }
            ViewBag.Cart = items;
            // total
            decimal total = 0;
            foreach (ItemCart item in items)
            {
                total += item.Price * item.Quantity;

            }
            ViewBag.Total = total;

            if (ModelState.IsValid)
            {
                    ctx.HoaDons.Add(bill);
                    ctx.SaveChanges();
                    return RedirectToAction("bill");
            }
            else
            {
                return View(bill);
            }
        }
    }
}

Customer/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Customer.Repository;
using Customer.Models;
using System.Collections.Generic;
using System.Linq;

namespace Customer.Controllers
{
    public class DetailController : Controller
    {
        WebsiteBanDoAnContext ctx = new WebsiteBanDoAnContext();
        IGioHangRepository giohangRepository = null;
        public DetailController(IGioHangRepository rep)
        {
            giohangRepository = rep;
        }
        public IActionResult Index()
        {
            ViewBag.Title = "Danh sách sản phẩm";
            List<MonAn> lst = giohangRepository.getAllGioHang();
            return View(lst);
        }
        public IActionResult Details(int id)
        {
            ViewBag.Title = "Xem chi tiết";
            List<DanhGium> lst = new List<DanhGium>();
            DanhGiaRepository danhGiaRepository = new DanhGiaRepository(ctx);
            List<DanhGium> temp = danhGiaRepository.getDanhGiaByMasp(id);
            ViewBag.khachhangs = danhGiaRepository.GetDanhGiaWithTenKh();
            foreach (DanhGium danhgia in ViewBag.khachhangs)
            {
                foreach (DanhGium dg in temp)
                {
                    if (dg.MaKh == danhgia.MaKhNavigation.MaKh)
                    {
                        lst.Add(danhgia);
                    }
                }
            }
            ViewBag.danhgias = lst;
            MonAn monan = ctx.MonAns.Where(x => x.MaSp == id).SingleOrDefault();
            return View(monan);
        }
    }
}

Customer/Views/Detail/Details.cshtml
@{
    Layout = "~/Views/Shared/layout.cshtml";
}
@model MonAn
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/css/detail.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" 
    crossorigin="anonymous">
    <!-- Css Styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
    <title>Document</title>
</head>

<body>
    <br>
    <div class="col-lg-12">
        <br>
        <div class="section-title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
    <br>
    <br>
@*    <div class="col-lg-12">
        <br>
        @foreach (var danhgia in ViewBag.danhgias)
        {
            <h2 style="color:#000;font-size:20px;text-align:center">@danhgia.MaKhNavigation.TenKh</h2>
        }
    </div>
    <br>
    <br>*@
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table class="table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th>Tên Món ăn</th>
                                    <th></th>
                                    <th>Giá</th>
                                    <th></th>
                                    <th>Số lượng</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="shoping__cart__item">
                                        <img src="~/images/@Model.HinhAnh" alt="" style="width:150px;height:100px">
                                    </td>
                                    <td class="shoping__cart__item">
                                    </td>
                                    <td class="shoping__cart__item">
                                        <h4>@Model.TenSp</h4>
                                    </td>
                                    <td class="shoping__cart__item">
                                    </td>
                                    <td class="shoping__cart__price">
                                        @Model.GiaSp <span>VNĐ</span>
                                    </td>
                                    <td class="shoping__cart__item">
                                    </td>
                                    <td class="shoping__cart__quantity">
                                        @using (Html.BeginForm("AddToCart","Cart", FormMethod.Post)){
						                    @Html.HiddenFor(m=>m.MaSp)
                                            <div class="quantity">
                                                <div class="pro-qty">
                                                    @Html.TextBox("SoLuong", "1")
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary" style="width:160px;height:40px">Thêm vào giỏ hàng</button>
					                    }
                                    </td>
                                </tr>
                            </tbody>
                        </table>  
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="shoping__checkout">
                        <h2 style="text-align:center">Mô tả</h2>
                        <br>
                        <ul>
                            <li><p style="color:#000;font-size:20px">@Model.MoTa</p></li>
                        </ul>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </section>
    <br>
    <!-- Js Plugins -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>
</body>

</html>

Customer/Views/Detail/Index.cshtml
@{
    Layout = "~/Views/Shared/layout.cshtml";
}
@model List<Customer.Models.MonAn>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/css/detail.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" 
    crossorigin="anonymous">
    <!-- Css Styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
    <title>Document</title>
</head>
<body>
    <br>
    <div class="col-lg-12">
        <br>
        <div class="section-title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
    <br>
    <div class="full" style="display:flex;flex-wrap:wrap">
        @foreach(var b in Model)
        {
            <div style="margin-left:100px">
                <div class="menu">
                    <img class="team" src="~/images/@b.HinhAnh">
                    <div class="text">
                        <div id="name">
                            <br>
                            <h2 style="text-align:center"><b>@b.TenSp</b></h2>
                            <h2 style="text-align:center"><b>@b.GiaSp <span>VNĐ</span></b></h2>
                        </div>
                        <br>
                        <div style="text-align:center">
                            @Html.ActionLink("Details","Details","Detail",new{id=b.MaSp},new{@class="site-btn"})
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="shoping__checkout" style="width: 350px;height: auto;text-align:center">
                        <h2>Mô tả</h2>
                        <br>
                        <ul>
                            <li><p style="color:#000;font-size:20px">@b.MoTa</p></li>
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
    @*<section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table class="table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th>Tên Món ăn</th>
                                    <th></th>
                                    <th>Giá</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            @foreach(var b in Model)
                            {
                                <tbody>
                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img src="~/images/@b.HinhAnh" alt="" style="width:150px;height:100px">
                                        </td>
                                        <td class="shoping__cart__item">
                                        </td>
                                        <td class="shoping__cart__item">
                                            <h4>@b.TenSp</h4>
                                        </td>
                                        <td class="shoping__cart__item">
                                        </td>
                                        <td class="shoping__cart__price">
                                            <h4>@b.GiaSp</h4> <span>VNĐ</span>
                                        </td>
                                        <td class="shoping__cart__item">
                                        </td>
                                        <td class="shoping__cart__item">
                                        </td>
                                        <td class="shoping__cart__item">
                                        </td>
                                        <td class="shoping__cart__item">
                                        </td>
                                        <td class="shoping__cart__item">
                                            @Html.ActionLink("Details","Details","Detail",new{id=b.MaSp},new{@class="site-btn"})
                                        </td>
                                    </tr>
                                </tbody>
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th></th>
                                        <th style="padding-top:2%;font-size:30px">Mô tả</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>
                                            <p style="padding-top:5%;color:#000;font-size:20px;width:800px;padding-left:250px">@b.MoTa</p>
                                        </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </thead>
                            }
                        </table>  
                    </div>
                </div>
            </div>
        </div>
    </section>*@
    <br>
    <!-- Js Plugins -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>
</body>

</html>